### ISSUE TITLE
Git shouldn't be written in all caps

### ISSUE THREAD

**Issue by whymarrh** [CTS-NL/GIT.Presentation#1]
| Correct | Incorrect |
| --- | --- |
| Git | GIT |

I wouldn't bother renaming the repository, but there are places in the presentation that can be updated.

**Comment by MitMaro** [comment]
I plan later to rename this repo and have it contain multiple presentations, I will take care of that then. I will fix the rest in the presentation.

**Comment by MitMaro** [comment]
Fixed in bd9e0f077439477c98de6503919a26a6da7a7a5a
